# Install script for directory: /home/jianliang.yjl/project/server-10.4

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/app/mariadb")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "RelWithDebInfo")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "0")
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Readme" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/." TYPE FILE FILES
    "/home/jianliang.yjl/project/server-10.4/README.md"
    "/home/jianliang.yjl/project/server-10.4/CREDITS"
    "/home/jianliang.yjl/project/server-10.4/COPYING"
    "/home/jianliang.yjl/project/server-10.4/THIRDPARTY"
    "/home/jianliang.yjl/project/server-10.4/EXCEPTIONS-CLIENT"
    )
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Readme" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/." TYPE FILE FILES
    "/home/jianliang.yjl/project/server-10.4/Docs/INSTALL-BINARY"
    "/home/jianliang.yjl/project/server-10.4/Docs/README-wsrep"
    )
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/jianliang.yjl/project/server-10.4/wsrep-lib/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/extra/readline/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/pcre/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/unittest/mytap/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/unittest/strings/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/unittest/examples/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/unittest/mysys/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/unittest/my_decimal/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/unittest/json_lib/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/unittest/sql/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/libmariadb/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/archive/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/blackhole/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/cassandra/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/connect/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/csv/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/example/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/federated/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/federatedx/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/heap/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/innobase/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/maria/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/mroonga/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/myisam/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/myisammrg/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/oqgraph/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/perfschema/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/rocksdb/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/sequence/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/sphinx/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/spider/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/test_sql_discovery/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/storage/tokudb/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/audit_null/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/auth_dialog/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/auth_ed25519/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/auth_examples/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/auth_gssapi/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/auth_pam/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/auth_pipe/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/auth_socket/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/aws_key_management/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/cracklib_password_check/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/daemon_example/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/debug_key_management/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/disks/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/example_key_management/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/feedback/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/file_key_management/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/fulltext/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/handler_socket/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/locale_info/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/metadata_lock_info/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/qc_info/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/query_response_time/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/server_audit/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/simple_password_check/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/sql_errlog/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/user_variables/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/userstat/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/versioning/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/win_auth_client/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/plugin/wsrep_info/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/include/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/dbug/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/strings/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/vio/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/mysys/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/mysys_ssl/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/client/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/extra/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/libservices/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/sql/share/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/tests/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/sql/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/mysql-test/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/mysql-test/lib/My/SafeProcess/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/sql-bench/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/man/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/scripts/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/support-files/cmake_install.cmake")
  include("/home/jianliang.yjl/project/server-10.4/extra/aws_sdk/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/home/jianliang.yjl/project/server-10.4/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
