# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget comp_err comp_sql factorial gen_lex_hash gen_lex_token)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target comp_err
add_executable(comp_err IMPORTED)

# Create imported target comp_sql
add_executable(comp_sql IMPORTED)

# Create imported target factorial
add_executable(factorial IMPORTED)

# Create imported target gen_lex_hash
add_executable(gen_lex_hash IMPORTED)

# Create imported target gen_lex_token
add_executable(gen_lex_token IMPORTED)

# Import target "comp_err" for configuration "RelWithDebInfo"
set_property(TARGET comp_err APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(comp_err PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/jianliang.yjl/project/server-10.4/extra/comp_err"
  )

# Import target "comp_sql" for configuration "RelWithDebInfo"
set_property(TARGET comp_sql APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(comp_sql PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/jianliang.yjl/project/server-10.4/scripts/comp_sql"
  )

# Import target "factorial" for configuration "RelWithDebInfo"
set_property(TARGET factorial APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(factorial PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/jianliang.yjl/project/server-10.4/dbug/factorial"
  )

# Import target "gen_lex_hash" for configuration "RelWithDebInfo"
set_property(TARGET gen_lex_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gen_lex_hash PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/jianliang.yjl/project/server-10.4/sql/gen_lex_hash"
  )

# Import target "gen_lex_token" for configuration "RelWithDebInfo"
set_property(TARGET gen_lex_token APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gen_lex_token PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/jianliang.yjl/project/server-10.4/sql/gen_lex_token"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
